"""
inspect_chunks.py
─────────────────
Shows every chunk stored in Qdrant for a specific hotel file.
Prints full payload: section, key, value, page, chunk_text, audit_trail.

Usage:
    python inspect_chunks.py
    → edit FILE_NAME below to the .md filename you want to inspect
"""

from qdrant_client import QdrantClient
from qdrant_client.models import Filter, FieldCondition, MatchValue

# ── Config ──────────────────────────────────────────────────
QDRANT_PATH     = "./qdrant_local"
COLLECTION_NAME = "hotel_contracts"

# ── Change this to any file you want to inspect ─────────────
FILE_NAME = "(HMA) Gateway Tirupati Thanapalli (07-Mar-2026_09-09_AM_IST).md"

# ─────────────────────────────────────────────────────────────

client = QdrantClient(path=QDRANT_PATH)

# ── Scroll all chunks for this file ─────────────────────────
results = client.scroll(
    collection_name=COLLECTION_NAME,
    scroll_filter=Filter(must=[
        FieldCondition(key="file_name", match=MatchValue(value=FILE_NAME))
    ]),
    limit=500,
    with_payload=True,
    with_vectors=False
)[0]

if not results:
    print(f"\n❌ No chunks found for file: '{FILE_NAME}'")
    print("   Check the file name matches exactly (case-sensitive).")
    client.close()
    exit()

# ── Sort by page_no then key_name for readable order ────────
results.sort(key=lambda p: (p.payload.get("page_no", 0), p.payload.get("key_name", "")))

# ── Print summary header ─────────────────────────────────────
print()
print("=" * 80)
print(f"  FILE     : {FILE_NAME}")
print(f"  HOTEL    : {results[0].payload.get('hotel_name', 'N/A')}")
print(f"  TYPE     : {results[0].payload.get('agreement_type', 'N/A')}")
print(f"  CONTRACT : {results[0].payload.get('contract_id', 'N/A')}")
print(f"  CHUNKS   : {len(results)}")
print("=" * 80)

# ── Print audit trail once at the top ───────────────────────
audit = results[0].payload.get("audit_trail", {})
if audit:
    print()
    print("  ── AUDIT TRAIL ──────────────────────────────────────")
    print(f"  AI Generated By : {audit.get('ai_generated_by', 'N/A')}")
    print(f"  Creation Time   : {audit.get('creation_time', 'N/A')}")
    print(f"  Approval Status : {audit.get('approval_status', 'N/A')}")
    print(f"  Maker           : {audit.get('maker_name', 'N/A')} ({audit.get('maker_email', 'N/A')})")
    print(f"  Maker Decision  : {audit.get('maker_decision', 'N/A')}  |  Date: {audit.get('maker_date', 'N/A')}")
    print(f"  Checker         : {audit.get('checker_name', 'N/A')} ({audit.get('checker_email', 'N/A')})")
    print(f"  Checker Decision: {audit.get('checker_decision', 'N/A')}  |  Date: {audit.get('checker_date', 'N/A')}")
    print()

# ── Print each chunk ─────────────────────────────────────────
current_section = None

for idx, point in enumerate(results, 1):
    p = point.payload

    section  = p.get("section",   "")
    key      = p.get("key_name",  "N/A")
    value    = p.get("value",     "")
    page     = p.get("page_no",   "?")
    chunk_text = p.get("chunk_text", "")

    # Print section header when it changes
    if section != current_section:
        current_section = section
        label = section if section else "⚠  (EMPTY SECTION)"
        print()
        print(f"  ┌─ SECTION: {label} {'─' * max(0, 55 - len(label))}")

    # Chunk header
    print(f"  │")
    print(f"  │  [{idx:02d}]  KEY   : {key}   (Page {page})")

    # Value — wrap long values
    if value:
        lines = value.split(". ")
        print(f"  │        VALUE : {lines[0]}")
        for ln in lines[1:]:
            if ln.strip():
                print(f"  │                {ln.strip()}")
    else:
        print(f"  │        VALUE : ⚠  EMPTY")

    # Full chunk_text (what was actually embedded)
    print(f"  │        ── EMBEDDED TEXT ──────────────────────────")
    for ln in chunk_text.splitlines():
        print(f"  │          {ln}")

    print(f"  │        ───────────────────────────────────────────")

print()
print(f"  └─ END — {len(results)} chunks total")
print()

client.close()